pull_request_rules:
  - name: merge dependabot PRs
    conditions:
      - 'author=dependabot[bot]'
      - 'status-success=Detekt'
      - 'status-success=Core'
      - 'status-success=Shared UI'
      - 'status-success=Distribution'
      - 'status-success=Server'
      - 'status-success=Android'
    actions:
      merge:
        method: squash
