events {}

http {
    server {
        listen 8082;

        client_max_body_size 3m;

        location ~* ^/api/users/[^/]+/profile-picture {
            proxy_pass http://pocket-id:1411;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_hide_header Cache-Control;
            proxy_hide_header Access-Control-Allow-Origin;
            add_header Access-Control-Allow-Origin $http_origin always;
            add_header Vary Origin always;
            add_header Cache-Control "no-store" always;
        }

        location / {
            proxy_pass http://pocket-id:1411;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
