ktor:
  deployment:
    port: 8081
    host: 0.0.0.0
  application:
    modules:
      - io.github.fgrutsch.cookmaid.ApplicationKt.module

database:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cookmaid}
  user: ${DATABASE_USER:cookmaid}
  password: ${DATABASE_PASSWORD:cookmaid}

oidc:
  issuer: ${OIDC_ISSUER:https://idp.localhost}
  jwks-url: ${OIDC_JWKS_URL:http://localhost:1411/.well-known/jwks.json}
