ktor:
  deployment:
    port: 8081
    host: 0.0.0.0
  application:
    modules:
      - io.github.fgrutsch.ApplicationKt.module

oidc:
  issuer: ${OIDC_ISSUER:http://idp.localhost}
  jwks-url: ${OIDC_JWKS_URL:http://localhost:1411/.well-known/jwks.json}
