-- Seed ~100 recipes for a given user.
-- Usage:
--   psql -d cookmaid -v user_id="'<your-uuid>'" -f sandbox/claude/seed_recipes.sql

-- Stagger created_at so cursor pagination has distinct values
INSERT INTO recipes (user_id, name, steps, tags, created_at) VALUES
(:user_id, 'Spaghetti Bolognese',       '{"Brown mince with onions","Add tomato sauce and simmer 20 min","Cook spaghetti","Serve with parmesan"}', '{"Pasta","Meat"}', now() - interval '100 minutes'),
(:user_id, 'Chicken Caesar Salad',      '{"Grill chicken breast","Chop romaine lettuce","Toss with caesar dressing and croutons"}', '{"Salad","Chicken"}', now() - interval '99 minutes'),
(:user_id, 'Margherita Pizza',          '{"Make dough and let rise","Spread tomato sauce","Top with mozzarella and basil","Bake at 250C for 10 min"}', '{"Pizza","Vegetarian"}', now() - interval '98 minutes'),
(:user_id, 'Beef Tacos',                '{"Season and cook ground beef","Warm tortillas","Assemble with salsa, cheese, and lettuce"}', '{"Mexican","Meat"}', now() - interval '97 minutes'),
(:user_id, 'Mushroom Risotto',          '{"Sauté mushrooms","Toast rice in butter","Add broth gradually while stirring","Finish with parmesan"}', '{"Rice","Vegetarian"}', now() - interval '96 minutes'),
(:user_id, 'Thai Green Curry',          '{"Fry curry paste in coconut milk","Add chicken and vegetables","Simmer 15 min","Serve with jasmine rice"}', '{"Thai","Chicken"}', now() - interval '95 minutes'),
(:user_id, 'Fish and Chips',            '{"Make beer batter","Coat fish fillets and deep fry","Fry chips until golden","Serve with tartar sauce"}', '{"British","Fish"}', now() - interval '94 minutes'),
(:user_id, 'Greek Salad',               '{"Chop tomatoes, cucumber, and onion","Add olives and feta","Drizzle with olive oil and oregano"}', '{"Salad","Vegetarian"}', now() - interval '93 minutes'),
(:user_id, 'Pad Thai',                  '{"Soak rice noodles","Stir fry shrimp and tofu","Add noodles and sauce","Top with peanuts and lime"}', '{"Thai","Noodles"}', now() - interval '92 minutes'),
(:user_id, 'Lasagna',                   '{"Make meat sauce","Layer with pasta sheets and bechamel","Repeat layers","Bake at 180C for 40 min"}', '{"Pasta","Meat"}', now() - interval '91 minutes'),
(:user_id, 'Chicken Stir Fry',          '{"Slice chicken and vegetables","Stir fry chicken until golden","Add vegetables and soy sauce","Serve over rice"}', '{"Asian","Chicken"}', now() - interval '90 minutes'),
(:user_id, 'Tomato Soup',               '{"Sauté onions and garlic","Add canned tomatoes and broth","Simmer 20 min","Blend until smooth"}', '{"Soup","Vegetarian"}', now() - interval '89 minutes'),
(:user_id, 'Beef Burger',               '{"Form beef patties and season","Grill 4 min per side","Toast buns","Assemble with toppings"}', '{"Burger","Meat"}', now() - interval '88 minutes'),
(:user_id, 'Pancakes',                  '{"Mix flour, eggs, milk, and sugar","Heat buttered pan","Pour batter and cook until bubbles form","Flip and serve"}', '{"Breakfast","Vegetarian"}', now() - interval '87 minutes'),
(:user_id, 'Shrimp Scampi',            '{"Cook linguine","Sauté garlic in butter","Add shrimp and white wine","Toss with pasta and parsley"}', '{"Pasta","Fish"}', now() - interval '86 minutes'),
(:user_id, 'Chicken Tikka Masala',      '{"Marinate chicken in yogurt and spices","Grill or bake chicken","Make tomato cream sauce","Combine and simmer"}', '{"Indian","Chicken"}', now() - interval '85 minutes'),
(:user_id, 'French Onion Soup',         '{"Caramelize onions slowly","Add beef broth and thyme","Ladle into bowls","Top with bread and gruyere, broil"}', '{"Soup","French"}', now() - interval '84 minutes'),
(:user_id, 'Vegetable Stir Fry',        '{"Chop mixed vegetables","Heat wok with oil","Stir fry vegetables","Add soy sauce and sesame oil"}', '{"Asian","Vegetarian"}', now() - interval '83 minutes'),
(:user_id, 'Banana Bread',              '{"Mash ripe bananas","Mix with flour, sugar, eggs, and butter","Pour into loaf pan","Bake at 175C for 60 min"}', '{"Baking","Breakfast"}', now() - interval '82 minutes'),
(:user_id, 'Pulled Pork Sandwich',      '{"Rub pork shoulder with spices","Slow cook 8 hours","Shred meat and mix with BBQ sauce","Serve on buns"}', '{"BBQ","Meat"}', now() - interval '81 minutes'),
(:user_id, 'Caprese Salad',             '{"Slice tomatoes and mozzarella","Arrange with fresh basil","Drizzle with olive oil and balsamic"}', '{"Salad","Vegetarian"}', now() - interval '80 minutes'),
(:user_id, 'Beef Stroganoff',           '{"Slice beef into strips","Sauté with onions and mushrooms","Add sour cream sauce","Serve over egg noodles"}', '{"Russian","Meat"}', now() - interval '79 minutes'),
(:user_id, 'Eggs Benedict',             '{"Poach eggs","Toast english muffins","Layer ham and eggs","Top with hollandaise sauce"}', '{"Breakfast","Eggs"}', now() - interval '78 minutes'),
(:user_id, 'Minestrone Soup',           '{"Sauté onion, celery, and carrot","Add beans, tomatoes, and broth","Add pasta and simmer","Season and serve"}', '{"Soup","Vegetarian"}', now() - interval '77 minutes'),
(:user_id, 'Teriyaki Salmon',           '{"Make teriyaki glaze","Brush salmon fillets","Bake at 200C for 12 min","Serve with steamed rice"}', '{"Japanese","Fish"}', now() - interval '76 minutes'),
(:user_id, 'Chocolate Chip Cookies',    '{"Cream butter and sugar","Add eggs and vanilla","Mix in flour and chocolate chips","Bake at 180C for 10 min"}', '{"Baking","Dessert"}', now() - interval '75 minutes'),
(:user_id, 'Chicken Fajitas',           '{"Slice chicken and peppers","Season with cumin and chili","Sauté until charred","Serve with warm tortillas"}', '{"Mexican","Chicken"}', now() - interval '74 minutes'),
(:user_id, 'Pumpkin Soup',              '{"Roast pumpkin chunks","Sauté onion and garlic","Add pumpkin and broth","Blend until smooth"}', '{"Soup","Vegetarian"}', now() - interval '73 minutes'),
(:user_id, 'Beef Chili',                '{"Brown ground beef","Add beans, tomatoes, and spices","Simmer 30 min","Serve with sour cream"}', '{"Mexican","Meat"}', now() - interval '72 minutes'),
(:user_id, 'Carbonara',                 '{"Cook spaghetti","Fry pancetta until crispy","Mix eggs with pecorino","Toss hot pasta with egg mixture off heat"}', '{"Pasta","Meat"}', now() - interval '71 minutes'),
(:user_id, 'Chicken Noodle Soup',       '{"Simmer chicken in broth","Remove and shred chicken","Add noodles and vegetables","Return chicken and serve"}', '{"Soup","Chicken"}', now() - interval '70 minutes'),
(:user_id, 'Guacamole',                 '{"Mash avocados","Mix in lime juice, onion, and cilantro","Season with salt","Serve with tortilla chips"}', '{"Mexican","Vegetarian"}', now() - interval '69 minutes'),
(:user_id, 'Lamb Chops',                '{"Season lamb with rosemary and garlic","Sear in hot pan 3 min per side","Rest 5 minutes","Serve with mint sauce"}', '{"Meat","Grilling"}', now() - interval '68 minutes'),
(:user_id, 'Fried Rice',                '{"Cook rice and let cool","Scramble eggs in wok","Add rice, vegetables, and soy sauce","Toss until heated through"}', '{"Asian","Rice"}', now() - interval '67 minutes'),
(:user_id, 'Blueberry Muffins',         '{"Mix flour, sugar, and baking powder","Combine milk, egg, and butter","Fold in blueberries","Bake at 190C for 20 min"}', '{"Baking","Breakfast"}', now() - interval '66 minutes'),
(:user_id, 'Pesto Pasta',               '{"Cook penne","Blend basil, pine nuts, garlic, and parmesan","Toss pasta with pesto","Top with extra parmesan"}', '{"Pasta","Vegetarian"}', now() - interval '65 minutes'),
(:user_id, 'BBQ Ribs',                  '{"Remove membrane from ribs","Apply dry rub","Slow cook at 130C for 3 hours","Glaze with BBQ sauce and broil"}', '{"BBQ","Meat"}', now() - interval '64 minutes'),
(:user_id, 'Cobb Salad',                '{"Chop lettuce, tomato, and avocado","Add chicken, bacon, egg, and blue cheese","Arrange in rows","Drizzle with vinaigrette"}', '{"Salad","Chicken"}', now() - interval '63 minutes'),
(:user_id, 'Shakshuka',                 '{"Sauté onions and peppers","Add tomatoes and spices","Make wells and crack in eggs","Cover and cook until eggs set"}', '{"Breakfast","Vegetarian"}', now() - interval '62 minutes'),
(:user_id, 'Tuna Poke Bowl',            '{"Cube fresh tuna","Marinate in soy sauce and sesame oil","Prepare rice and toppings","Assemble bowl"}', '{"Japanese","Fish"}', now() - interval '61 minutes'),
(:user_id, 'Chicken Parmesan',          '{"Bread chicken cutlets","Pan fry until golden","Top with marinara and mozzarella","Bake until cheese melts"}', '{"Italian","Chicken"}', now() - interval '60 minutes'),
(:user_id, 'Lentil Curry',              '{"Cook lentils until tender","Sauté onion with curry spices","Add tomatoes and lentils","Simmer 15 min"}', '{"Indian","Vegetarian"}', now() - interval '59 minutes'),
(:user_id, 'Grilled Cheese Sandwich',   '{"Butter bread slices","Layer cheese between bread","Grill in pan until golden on both sides"}', '{"Sandwich","Vegetarian"}', now() - interval '58 minutes'),
(:user_id, 'Clam Chowder',              '{"Cook bacon and onions","Add potatoes and broth","Add clams and cream","Simmer until potatoes are tender"}', '{"Soup","Fish"}', now() - interval '57 minutes'),
(:user_id, 'Chicken Wings',             '{"Season wings with salt and baking powder","Bake at 220C for 40 min","Toss with buffalo sauce","Serve with blue cheese dip"}', '{"Chicken","Grilling"}', now() - interval '56 minutes'),
(:user_id, 'Ratatouille',               '{"Slice zucchini, eggplant, and tomatoes","Layer in baking dish","Drizzle with herb oil","Bake at 180C for 45 min"}', '{"French","Vegetarian"}', now() - interval '55 minutes'),
(:user_id, 'Sushi Rolls',               '{"Cook sushi rice","Place rice on nori sheet","Add fillings and roll tightly","Cut into pieces"}', '{"Japanese","Fish"}', now() - interval '54 minutes'),
(:user_id, 'Shepherd''s Pie',           '{"Cook lamb mince with vegetables","Make mashed potatoes","Layer meat in dish, top with potato","Bake at 200C for 25 min"}', '{"British","Meat"}', now() - interval '53 minutes'),
(:user_id, 'Smoothie Bowl',             '{"Blend frozen berries with banana and yogurt","Pour into bowl","Top with granola, fruit, and seeds"}', '{"Breakfast","Vegetarian"}', now() - interval '52 minutes'),
(:user_id, 'Chicken Quesadilla',        '{"Shred cooked chicken","Layer chicken and cheese on tortilla","Fold and cook in pan until crispy","Cut and serve with salsa"}', '{"Mexican","Chicken"}', now() - interval '51 minutes'),
(:user_id, 'Gazpacho',                  '{"Blend tomatoes, cucumber, pepper, and garlic","Add olive oil and vinegar","Chill for 2 hours","Serve cold"}', '{"Spanish","Vegetarian"}', now() - interval '50 minutes'),
(:user_id, 'Pork Schnitzel',            '{"Pound pork cutlets thin","Bread with flour, egg, and breadcrumbs","Pan fry in oil until golden","Serve with lemon"}', '{"German","Meat"}', now() - interval '49 minutes'),
(:user_id, 'Avocado Toast',             '{"Toast sourdough bread","Mash avocado with lime and salt","Spread on toast","Top with chili flakes and egg"}', '{"Breakfast","Vegetarian"}', now() - interval '48 minutes'),
(:user_id, 'Miso Soup',                 '{"Heat dashi broth","Dissolve miso paste","Add tofu and wakame","Garnish with green onions"}', '{"Japanese","Soup"}', now() - interval '47 minutes'),
(:user_id, 'Chicken Shawarma',          '{"Marinate chicken in yogurt and spices","Grill or bake until charred","Slice thinly","Serve in pita with garlic sauce"}', '{"Middle Eastern","Chicken"}', now() - interval '46 minutes'),
(:user_id, 'Apple Pie',                 '{"Make pie crust","Peel and slice apples","Toss with sugar and cinnamon","Fill crust and bake at 190C for 45 min"}', '{"Baking","Dessert"}', now() - interval '45 minutes'),
(:user_id, 'Dan Dan Noodles',           '{"Cook egg noodles","Make spicy sesame sauce","Brown pork mince with Sichuan pepper","Toss noodles with sauce and pork"}', '{"Chinese","Noodles"}', now() - interval '44 minutes'),
(:user_id, 'Bruschetta',                '{"Dice tomatoes with basil and garlic","Toast baguette slices","Top bread with tomato mixture","Drizzle with olive oil"}', '{"Italian","Vegetarian"}', now() - interval '43 minutes'),
(:user_id, 'Lamb Tagine',               '{"Brown lamb pieces","Add onions, dried fruits, and spices","Add broth and simmer 90 min","Serve with couscous"}', '{"Moroccan","Meat"}', now() - interval '42 minutes'),
(:user_id, 'Omelette',                  '{"Beat eggs with salt and pepper","Melt butter in pan","Pour eggs and cook until edges set","Add fillings, fold and serve"}', '{"Breakfast","Eggs"}', now() - interval '41 minutes'),
(:user_id, 'Pho',                       '{"Simmer beef bones with star anise and cinnamon 4 hours","Cook rice noodles","Slice beef thinly","Assemble and pour hot broth over"}', '{"Vietnamese","Soup"}', now() - interval '40 minutes'),
(:user_id, 'Stuffed Peppers',           '{"Halve and seed bell peppers","Mix rice, meat, and tomato sauce","Fill peppers","Bake at 180C for 30 min"}', '{"Meat","Vegetarian"}', now() - interval '39 minutes'),
(:user_id, 'Tiramisu',                  '{"Mix mascarpone with egg yolks and sugar","Dip ladyfingers in espresso","Layer cream and biscuits","Chill overnight and dust with cocoa"}', '{"Italian","Dessert"}', now() - interval '38 minutes'),
(:user_id, 'Korean Bibimbap',           '{"Cook rice","Prepare assorted vegetable toppings","Fry egg sunny side up","Assemble in bowl with gochujang"}', '{"Korean","Rice"}', now() - interval '37 minutes'),
(:user_id, 'Croque Monsieur',           '{"Layer ham and gruyere on bread","Spread bechamel on top","Bake at 200C until golden","Serve hot"}', '{"French","Sandwich"}', now() - interval '36 minutes'),
(:user_id, 'Sweet Potato Fries',        '{"Cut sweet potatoes into sticks","Toss with oil and salt","Bake at 220C for 25 min","Serve with aioli"}', '{"Vegetarian","Snack"}', now() - interval '35 minutes'),
(:user_id, 'Chicken Korma',             '{"Fry onions until golden","Add chicken and spices","Pour in cream and ground almonds","Simmer 20 min"}', '{"Indian","Chicken"}', now() - interval '34 minutes'),
(:user_id, 'Prawn Cocktail',            '{"Cook and chill prawns","Make marie rose sauce","Arrange lettuce in glasses","Top with prawns and sauce"}', '{"British","Fish"}', now() - interval '33 minutes'),
(:user_id, 'Gnocchi with Sage Butter',  '{"Boil gnocchi until they float","Brown butter in pan with sage leaves","Toss gnocchi in sage butter","Top with parmesan"}', '{"Italian","Vegetarian"}', now() - interval '32 minutes'),
(:user_id, 'Chili Con Carne',           '{"Brown beef mince","Add onions, garlic, and chili","Add beans and tomatoes","Simmer 45 min"}', '{"Mexican","Meat"}', now() - interval '31 minutes'),
(:user_id, 'Waffles',                   '{"Mix waffle batter with flour, eggs, milk, and butter","Heat waffle iron","Cook until golden","Serve with maple syrup"}', '{"Breakfast","Vegetarian"}', now() - interval '30 minutes'),
(:user_id, 'Salmon Teriyaki Bowl',      '{"Glaze salmon with teriyaki sauce","Bake at 200C for 12 min","Cook rice and prepare edamame","Assemble bowl"}', '{"Japanese","Fish"}', now() - interval '29 minutes'),
(:user_id, 'Waldorf Salad',             '{"Dice apples and celery","Add walnuts and grapes","Toss with mayonnaise","Serve on lettuce leaves"}', '{"Salad","Vegetarian"}', now() - interval '28 minutes'),
(:user_id, 'Butter Chicken',            '{"Marinate chicken in yogurt and spices","Grill chicken pieces","Make tomato butter sauce","Simmer chicken in sauce"}', '{"Indian","Chicken"}', now() - interval '27 minutes'),
(:user_id, 'Ceviche',                   '{"Dice fresh white fish","Marinate in lime juice 30 min","Add onion, cilantro, and chili","Serve chilled with tostadas"}', '{"Peruvian","Fish"}', now() - interval '26 minutes'),
(:user_id, 'Chicken Fried Rice',        '{"Cook and cool rice","Scramble eggs in wok","Add chicken, rice, peas, and soy sauce","Stir fry until heated"}', '{"Asian","Rice"}', now() - interval '25 minutes'),
(:user_id, 'Crème Brûlée',             '{"Heat cream with vanilla","Whisk into egg yolks and sugar","Bake in water bath at 150C for 40 min","Torch sugar topping"}', '{"French","Dessert"}', now() - interval '24 minutes'),
(:user_id, 'Falafel Wrap',              '{"Blend chickpeas with herbs and spices","Form patties and fry","Warm pita bread","Assemble with tahini and salad"}', '{"Middle Eastern","Vegetarian"}', now() - interval '23 minutes'),
(:user_id, 'Tom Yum Soup',              '{"Boil broth with lemongrass and galangal","Add mushrooms and shrimp","Season with lime juice and fish sauce","Garnish with cilantro"}', '{"Thai","Soup"}', now() - interval '22 minutes'),
(:user_id, 'Steak with Chimichurri',    '{"Season steak with salt and pepper","Grill to desired doneness","Blend parsley, garlic, oil, and vinegar","Serve steak with chimichurri"}', '{"Argentinian","Meat"}', now() - interval '21 minutes'),
(:user_id, 'Vegetable Lasagna',         '{"Sauté spinach and zucchini","Layer with pasta sheets and ricotta","Top with bechamel and mozzarella","Bake at 180C for 40 min"}', '{"Pasta","Vegetarian"}', now() - interval '20 minutes'),
(:user_id, 'French Toast',              '{"Whisk eggs with milk, cinnamon, and vanilla","Dip bread slices","Cook in buttered pan until golden","Serve with maple syrup"}', '{"Breakfast","Vegetarian"}', now() - interval '19 minutes'),
(:user_id, 'Beef Pho',                  '{"Make aromatic beef broth","Cook rice noodles","Slice raw beef thinly","Pour hot broth over noodles and beef"}', '{"Vietnamese","Noodles"}', now() - interval '18 minutes'),
(:user_id, 'Hummus',                    '{"Blend chickpeas with tahini and lemon","Add garlic and olive oil","Blend until smooth","Serve with pita"}', '{"Middle Eastern","Vegetarian"}', now() - interval '17 minutes'),
(:user_id, 'Duck Confit',               '{"Salt duck legs overnight","Slow cook in duck fat at 130C for 3 hours","Crisp skin under broiler","Serve with potatoes"}', '{"French","Meat"}', now() - interval '16 minutes'),
(:user_id, 'Granola',                   '{"Mix oats, nuts, and honey","Spread on baking sheet","Bake at 150C for 30 min, stirring halfway","Cool and store"}', '{"Breakfast","Vegetarian"}', now() - interval '15 minutes'),
(:user_id, 'Lobster Bisque',            '{"Sauté lobster shells with aromatics","Add tomato paste and brandy","Simmer with cream","Strain and serve with lobster meat"}', '{"French","Soup"}', now() - interval '14 minutes'),
(:user_id, 'Chicken Gyros',             '{"Marinate chicken in lemon and oregano","Grill and slice thinly","Warm pita","Assemble with tzatziki and vegetables"}', '{"Greek","Chicken"}', now() - interval '13 minutes'),
(:user_id, 'Brownies',                  '{"Melt chocolate and butter","Whisk in sugar and eggs","Fold in flour","Bake at 180C for 25 min"}', '{"Baking","Dessert"}', now() - interval '12 minutes'),
(:user_id, 'Paella',                    '{"Sauté chicken and chorizo","Add rice and saffron broth","Arrange shrimp and mussels on top","Cook until rice absorbs liquid"}', '{"Spanish","Rice"}', now() - interval '11 minutes'),
(:user_id, 'Nicoise Salad',             '{"Boil eggs and green beans","Arrange lettuce, tuna, potatoes, and olives","Add eggs and beans","Dress with vinaigrette"}', '{"French","Salad"}', now() - interval '10 minutes'),
(:user_id, 'Macaroni and Cheese',       '{"Cook macaroni","Make cheese sauce with butter, flour, and cheddar","Combine pasta and sauce","Bake at 190C for 20 min"}', '{"Pasta","Vegetarian"}', now() - interval '9 minutes'),
(:user_id, 'Spring Rolls',              '{"Prepare rice paper wrappers","Fill with shrimp, noodles, and herbs","Roll tightly","Serve with peanut dipping sauce"}', '{"Vietnamese","Snack"}', now() - interval '8 minutes'),
(:user_id, 'Chicken Marsala',           '{"Pound and flour chicken breasts","Pan fry until golden","Add mushrooms and marsala wine","Simmer until sauce thickens"}', '{"Italian","Chicken"}', now() - interval '7 minutes'),
(:user_id, 'Energy Balls',              '{"Mix oats, peanut butter, honey, and chocolate chips","Roll into balls","Refrigerate 30 min","Store in fridge"}', '{"Snack","Vegetarian"}', now() - interval '6 minutes'),
(:user_id, 'Moussaka',                  '{"Layer sliced eggplant and meat sauce","Top with bechamel","Bake at 180C for 45 min","Let rest before serving"}', '{"Greek","Meat"}', now() - interval '5 minutes'),
(:user_id, 'Açaí Bowl',                '{"Blend frozen açaí with banana and juice","Pour into bowl","Top with granola, berries, and coconut","Drizzle with honey"}', '{"Breakfast","Vegetarian"}', now() - interval '4 minutes'),
(:user_id, 'Beef Wellington',           '{"Sear beef fillet","Wrap in mushroom duxelles and puff pastry","Chill 30 min","Bake at 200C for 25 min"}', '{"British","Meat"}', now() - interval '3 minutes'),
(:user_id, 'Tzatziki',                  '{"Grate and drain cucumber","Mix with yogurt, garlic, and dill","Add olive oil and lemon juice","Chill before serving"}', '{"Greek","Vegetarian"}', now() - interval '2 minutes'),
(:user_id, 'Churros',                   '{"Make choux pastry dough","Pipe into hot oil and fry until golden","Roll in cinnamon sugar","Serve with chocolate sauce"}', '{"Spanish","Dessert"}', now() - interval '1 minute');

-- Add a few free-text ingredients to each recipe for realism
INSERT INTO recipe_ingredients (recipe_id, free_text_name, quantity)
SELECT r.id, 'Salt', NULL FROM recipes r WHERE r.user_id = :user_id;

INSERT INTO recipe_ingredients (recipe_id, free_text_name, quantity)
SELECT r.id, 'Olive oil', 2 FROM recipes r WHERE r.user_id = :user_id;

INSERT INTO recipe_ingredients (recipe_id, free_text_name, quantity)
SELECT r.id, 'Black pepper', NULL FROM recipes r WHERE r.user_id = :user_id;
